from dataclasses import dataclass
from enum import Enum

class TokenType(Enum):
    TkDot = "."
    TkDoubleDot = ".."
    TkTripleDot = "..."
    TkColon = ":"
    TkDoubleColon = "::"
    TkComma = ","
    TkEqual = "="
    TkAmpersand = "&"
    TkVerticalBar = "|"
    TkCaret = "^"
    TkTilde = "~"
    TkDoubleAmpersand = "&&"
    TkDoubleVerticalBar = "||"
    TkExclamation = "!"
    TkLeftAngleBracket = "<"
    TkRightAngleBracket = ">"
    TDoubleLeftAngleBracket = "<<"
    TDoubleRightAngleBracket = ">>"
    TkTripleLeftAngleBracket = "<<<"
    TkTripleRightAngleBracket = ">>>"
    TkLeftParenthesis = "("
    TkRightParenthesis = ")"
    TkLeftBrace = "{"
    TkRightBrace = "}"
    TkLeftBracket = "["
    TkRightBracket = "]"
    TkQuestionMark = "?"
    TkDoubleEqual = "=="
    TkExclamationEqual = "!="
    TkLeftAngleEqual = "<="
    TkRightAngleEqual = ">="
    TkPlus = "+"
    TkHyphen = "-"
    TkAsterisk = "*"
    TkForwardSlash = "/"
    TkDoubleForwardSlash = "//"
    TkPercent = "%"
    TkDoubleAstrix = "**"
    TkDoubleQuestionMark = "??"
    TkQuestionMarkColon = "?:"
    TkRightArrow = "->"
    TkDoublePlus = "++"
    TkDoubleHyphen = "--"
    TkAt = "@"
    TkDoubleFatArrow = "<=>"
    TkPipe = "|>"
    TkSemicolon = ";"
    TkUnderscore = "_"
    TkEOF = "\0"
    TkWhitespace = " "
    TkNewLine = "\n"

    KwMod = "mod"
    KwUse = "use"
    KwEnum = "enum"
    KwIn = "in"
    KwPub = "pub"
    KwProt = "prot"
    KwPriv = "priv"
    KwPart = "part"
    KwAsync = "async"
    KwFun = "fun"
    KwMut = "mut"
    KwLet = "let"
    KwIf = "if"
    KwElif = "elif"
    KwElse = "else"
    KwWhile = "while"
    KwFor = "for"
    KwDo = "do"
    KwMatch = "match"
    KwCase = "case"
    KwReturn = "return"
    KwYield = "yield"
    KwCls = "cls"
    KwAwait = "await"
    KwWhere = "where"
    KwTrue = "true"
    KwFalse = "false"
    KwAs = "as"
    KwSup = "sup"
    KwWith = "with"

    LxIdentifier = r"[_a-zA-Z][_a-zA-Z0-9]*"
    LxBinDigits = r"0b[01]+"
    LxDecDigits = r"[0-9]+"
    LxHexDigits = r"0x[0-9a-fA-F]+"
    LxDoubleQuoteStr = r"\".*\""
    LxSingleQuoteChr = r"'.?'"
    LxRegex = r"r\".*\""


@dataclass
class Token:
    token_metadata: str
    token_type: TokenType
